url: pintsflightandbites.com
description:
title: Alex J Guardado
markdown: kramdown
highlighter: rouge

#local dev url
#url: "http://localhost:3000"

# exclude npm related files
exclude: [']package.json', 'node_modules']
